### ISSUE TITLE
Potential Performance Improvements

### ISSUE THREAD

**Issue by DavisBrown723** [mrvivacious/porNo_open_source#1]
As noted in the README, performance is a crucial element to the success of this application. This application also employs the use of large hard coded arrays. Due to the nature of the search, we can potentially implement a broad-phase for discarding obvious, non-matching urls.

Solution:
You can transform your list to have an array of websites indexed by the first character each url starts with. The transformation of this list would likely have to be done with a script or by hand, because we (assumedly) don't have the time to manipulate it during runtime.
ex: 
```
[
     ["a", ["awebsite","anotherwebsite"]],
     ["b", ["bxxxxx","byyyy"]]
     ["c", ["c.dummyurl"]]
]
```
When determining if a string exists in the list, you may trim your potential matches significantly, by grabbing the list that corresponds to the first character in the url being checked.
In the above example, if we were checking the existence of the url `"bzyz"` in the list, we need only check the list `["bxxxxx","byyyy"]`. This drastically improves our worst case scenario for url searches.

Disclaimer:
I have very limited knowledge of JS so the details of the implementation would be up to you, whether it's nested arrays or a hashmap. Ideally we could make use of a [Trie](https://en.wikipedia.org/wiki/Trie), but the creation of such a datastructure with so many elements would cause more trouble than it's worth in such a small and runtime-oriented application.

Let me know if there's anything I can clarify,
Congrats on the release brother

**Comment by mrvivacious** [comment]
Hi Davis!
What do you think of creating a massive hashmap as such: [link: true, link2: true,...] ?
The lookup time on average should be O(1), worst case O(n) (no worse than the current state).
I'll run tests with the current implementation, the dictionary sorted by letters, and the hashmap ideas. I'll share those times here when I finish.

**Comment by DavisBrown723** [comment]
A map would probably be the easiest since I'm guessing there is a library construct built in for it.

At the end of the day I think both options will yield worthy results.

**Comment by mrvivacious** [comment]
Created a hashmap of porn domains to assist with the runtime -- lists.js 
Thank you again, Davis

**Comment by mrvivacious** [comment]
Statistics from tests:
Lookup average case with array of 1,300 ~ elements: 3 ms
Lookup average case with hashmap of 25,000 ~ elements: 2.5 ms

I am surprised to see a relatively small difference in the times but I am happy with the new implementation :)
