### ISSUE TITLE
porn site visible

### ISSUE THREAD

**Issue by randomguy7878** [mrvivacious/porNo_open_source#15]
https://niceporn.tv

**Comment by randomguy7878** [comment]
https://www.porntry.com

**Comment by randomguy7878** [comment]
http://www.bigporn.com

**Comment by mrvivacious** [comment]
Thank you so much 

Open the PorNo! app for a few seconds and it should be updated
I will add these links to the source in the next update

**Comment by mrvivacious** [comment]
https://github.com/mrvivacious/porNo_open_source/commit/7a7ceef178cab8a578072281f3b75ea61946cbe9

https://github.com/mrvivacious/porNo_open_source/commit/b79b17a33b98e547dc6cb88ba4c2606bd84d3bee
